databases:
  - name: my-campus
    databaseName: my_campus
    user: my_campus

services:
  - type: web
    name: my-campus
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my_campus
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false